defmodule Hova.Data do
  def sentences do
    [
      "You're now tuned into the motherfucking greatest",
      "Turn the music up in the headphones",
      "Tim, you can go and brush your shoulder off nigga",
      "I got you, yeah",
      "If you feeling like a pimp nigga, go and brush your shoulders off",
      "Ladies is pimps too, go and brush your shoulders off",
      "Niggas is crazy baby, don't forget that boy told you",
      "Get, that, dirt off your shoulder",
      "I probably owe it to you all, proud to be locked by the force",
      "Trying to hustle some things, that go with the Porsche",
      "Feeling no remorse, feeling like my hand was forced",
      "Middle finger to the law, nigga griping my balls",
      "All the ladies they love me, from the bleachers they screaming",
      "All the ballers is bouncing they like the way I be leaning",
      "All the rappers be hating, off the track that I'm making",
      "But all the hustlers they love it just to see one of us make it",
      "Came from the bottom the bottom, to the \"Top of the Pops\"",
      "Nigga London, Japan and I'm straight off the block",
      "Like a running back, get it man, I'm straight off the block",
      "I can run it back nigga 'cause I'm straight with the Roc",
      "You gotta get, that, dirt off your shoulder",
      "You gotta get, that, dirt off your shoulder",
      "You gotta get, that, dirt off your shoulder",
      "You gotta get, that, dirt off your shoulder",
      "Your homey Hov' in position, in the kitchen with soda",
      "I just whipped up a watch, trying to get me a Rover",
      "Trying to stretch out the coca, like a wrestler, yes sir",
      "Keep the Heckler close, you know them smokers'll test you",
      "But like, fifty-two cards when I'm, I'm through dealing",
      "Now fifty-two bars come out, now you feel 'em",
      "Now, fifty-two cars roll out, remove ceiling",
      "In case fifty-two broads come out, now you chilling",
      "with a boss bitch of course S.C. on the sleeve",
      "At the 40/40 club, ESPN on the screen",
      "I paid a grip for the jeans, plus the slippers is clean",
      "No chrome on the wheels, I'm a grown-up for real",
      "Your boy back in the building, Brooklyn we back on the map",
      "Me and my beautiful beeeeeeeitch in the back of that 'Bach",
      "I'm the realest that run it, I just happen to rap",
      "I ain't gotta clap at 'em, niggas scared of that black",
      "I drop that +Black, Album+ then I back, out it",
      "As the best rapper alive nigga ask about me",
      "From Bricks to Billboards, from grams to Grammies",
      "The O's to opposite, Orphan Annie",
      "You gotta pardon Jay, for selling out the Garden in a day",
      "I'm like a young Marvin in his hey",
      "I'm a hustler homey, you a customer crony",
      "Got some, dirt on my shoulder, could you brush it off for me?",
      "You're now tuned into the motherfucking greatest",
      "Best rapper alive, best rapper alive",
      "If you're having girl problems I feel bad for you son",
      "I got 99 problems but a bitch ain't one",
      "I got the rap patrol on the gat patrol",
      "Foes that wanna make sure my casket's closed",
      "Rap critics that say he's \"Money Cash Hoes\"",
      "I'm from the hood stupid what type of facts are those",
      "If you grew up with holes in your zapatos",
      "You'd celebrate the minute you was having dough",
      "I'm like fuck critics you can kiss my whole asshole",
      "If you don't like my lyrics you can press fast forward",
      "Got beef with radio if I don't play they show",
      "They don't play my hits well I don't give a shit SO",
      "Rap mags try and use my black ass",
      "So advertisers can give em more cash for ads...fuckers",
      "I don't know what you take me as",
      "or understand the intelligence that Jay-Z has",
      "I'm from rags to riches nigga I ain't dumb",
      "I got 99 problems but a bitch ain't one",
      "Hit me",
      "99 Problems but a bitch ain't one",
      "If you having girl problems I feel bad for you son",
      "I got 99 problems but a bitch ain't one",
      "Hit me",
      "The year is '94 and in my trunk is raw",
      "In my rear view mirror is the mother fucking law",
      "I got two choices yall pull over the car or",
      "bounce on the double put the pedal to the floor",
      "Now I ain't trying to see no highway chase with jake",
      "Plus I got a few dollars I can fight the case",
      "So I...pull over to the side of the road",
      "And I heard \"Son do you know why I'm stopping you for?\"",
      "Cause I'm young and I'm black and my hat's real low",
      "Do I look like a mind reader sir, I don't know",
      "Am I under arrest or should I guess some mo?",
      "\"Well you was doing fifty five in a fifty four\"",
      "\"License and registration and step out of the car\"",
      "\"Are you carrying a weapon on you I know a lot of you are\"",
      "I ain't stepping out of shit all my papers legit",
      "\"Do you mind if I look round the car a little bit?\"",
      "Well my glove compartment is locked so is the trunk and the back",
      "And I know my rights so you gon' need a warrant for that",
      "\"Aren't you sharp as a tack are some type of lawyer or something?\"",
      "\"Or somebody important or something?\"",
      "Nah I ain't passed the bar but I know a little bit",
      "Enough that you won't illegally search my shit",
      "\"Well see how smart you are when the K-9's come\"",
      "I got 99 problems but a bitch ain't one",
      "Hit me",
      "Now once upon a time not too long ago",
      "A nigga like myself had to strong arm a hoe",
      "This is not a hoe in the sense of having a pussy",
      "But a pussy having no God Damn sense, try and push me",
      "I tried to ignore him and talk to the Lord",
      "Pray for him, cause some fools just love to perform",
      "You know the type loud as a motor bike",
      "But wouldn't bust a grape in a fruit fight",
      "The only thing that's gonna happen is i'mma get to clapping",
      "He and his boys gon' be yapping to the captain",
      "And there I go trapped in the kit kat again",
      "Back through the system with the riff raff again",
      "Fiends on the floor scratching again",
      "Paparazzi's with they cameras snapping them",
      "D.A. tried to give the nigga the shaft again",
      "Half-a-mil for bail cause I'm African",
      "All because this fool was harrassin' them",
      "Trying to play the boy like hes saccarin",
      "But ain't nothing sweet 'bout how I hold my gun",
      "I got 99 problems but being a bitch ain't one",
      "Hit me",
      "You're crazy for this one Rick",
      "It's your boy",
      "Thank you, thank you, thank you, you're far too kind",
      "Now can I get an encore, do you want more",
      "Cookin raw with the Brooklyn boy",
      "So for one last time I need y'all to roar",
      "Now what the hell are you waitin for",
      "After me, there shall be no more",
      "So for one last time, nigga make some noise",
      "Who you know fresher than Hov'? Riddle me that",
      "The rest of y'all know where I'm lyrically at",
      "Can't none of y'all mirror me back",
      "Yeah hearin me rap is like hearin G. Rap in his prime",
      "I'm, young H.O., rap's Grateful Dead",
      "Back to take over the globe, now break bread",
      "I'm in, Boeing jets, Global Express",
      "Out the country but the blueberry still connect",
      "On the low but the yacht got a triple deck",
      "But when you Young, what the fuck you expect? Yep, yep",
      "Grand openin, grand closin",
      "God damn your man Hov' cracked the can open again",
      "Who you gon' find doper than him with no pen",
      "just draw off inspiration",
      "Soon you gon' see you can't replace him",
      "with cheap imitations for DESE GENERATIONS",
      "{What the hell are you waiting forrrr?}",
      "Look what you made me do, look what I made for you",
      "Knew if I paid my dues, how will they pay you",
      "When you first come in the game, they try to play you",
      "Then you drop a couple of hits, look how they wave to you",
      "From Marcy to Madison Square",
      "To the only thing that matters in just a matter of years (yea)",
      "As fate would have it, Jay's status appears",
      "to be at an all-time high, perfect time to say goodbye",
      "When I come back like Jordan, wearin the 4-5",
      "It ain't to play games witchu",
      "It's to aim at you, probably maim you",
      "If I owe you I'm blowin you to smithereeens",
      "Cocksucker take one for your team",
      "And I need you to remember one thing (one thing)",
      "I came, I saw, I conquered",
      "From record sales, to sold out concerts",
      "So muh'fucker if you want this encore",
      "I need you to scream, 'til your lungs get sore",
      "OWWWW! It's star time",
      "This man is MADE! He's KILLIN all y'all jive turkeys",
      "Do y'all want more of the Jigga man?",
      "Well if y'all want more of the Jigga man",
      "Then I need y'all to help me, bring him back to stage",
      "Say Hova, c'mon say it!",
      "HO-VA! HO-VA! Are y'all out there?",
      "Are y'all out there? C'mon, louder!",
      "Yeah, now see that's what I'm talkin bout",
      "They love you Jigga - they love you Jigga!",
      "I like the way this one feel",
      "It's so muh'fuckin soulful man!",
      "(Whoaaaaaahhhh, whoahhhhhhhhhhhhh, whoahhhhhhhhhhhhh)",
      "Yeah  okay",
      "So this here is the victory lap",
      "Then I'm lea-vin, that's how you get me back",
      "After a year of them 16's, it's one point two",
      "And that's two point four, and I'm only doin two",
      "You wanted to gain attention new dudes",
      "I can get you BET and TRL too",
      "You wanna be in the public, send your budget",
      "Well fuck it, I ain't budgin!",
      "Young did it to death, you gotta love it",
      "Record companies told me I couldn't cut it",
      "Now look at me, all star-studded",
      "Golfer above par like I putted",
      "All cause the shit I uttered, was utterly ridiculous",
      "How sick is this?",
      "You want to bang, send Kanye change, send Just some dust",
      "Send Hip a grip, then you got' spit",
      "A little somethin like this, WOO!",
      "Uhh, uh uh uh",
      "It's big pimpin baby..",
      "It's big pimpin, spendin G's",
      "Feel me.. uh-huh uhh, uh-huh..",
      "Ge-ge-geyeah, geyeah",
      "Ge-ge-geyeah, geyeah..",
      "You know I - thug em, fuck em, love em, leave em",
      "Cause I don't fuckin need em",
      "Take em out the hood, keep em lookin good",
      "But I don't fuckin feed em",
      "First time they fuss I'm breezin",
      "Talkin bout, \"What's the reasons?\"",
      "I'm a pimp in every sense of the word, bitch",
      "Better trust than believe em",
      "In the cut where I keep em",
      "til I need a nut, til I need to beat the guts",
      "Then it's, beep beep and I'm pickin em up",
      "Let em play with the dick in the truck",
      "Many chicks wanna put Jigga fist in cuffs",
      "Divorce him and split his bucks",
      "Just because you got good head, I'ma break bread",
      "so you can be livin it up? Shit I..",
      "parts with nothin, y'all be frontin",
      "Me give my heart to a woman?",
      "Not for nothin, never happen",
      "I'll be forever mackin",
      "Heart cold as assassins, I got no passion",
      "I got no patience",
      "And I hate waitin..",
      "Hoe get yo' ass in",
      "And let's RI-I-I-I-I-IDE.. check em out now",
      "RI-I-I-I-I-IDE, yeah",
      "And let's RI-I-I-I-I-IDE.. check em out now",
      "RI-I-I-I-I-IDE, yeah",
      "We doin.. big pimpin, we spendin G's",
      "Check em out now",
      "Big pimpin, on B.L.A.D.'s",
      "We doin.. big pimpin up in N.Y.C.",
      "It's just that Jigga Man, Pimp C, and B-U-N B",
      "Yo yo yo.. big pimpin, spendin G's",
      "We doin - big pimpin, on B.L.A.D.'s",
      "We doin.. big pimpin up in N.Y.C.",
      "It's just that Jigga Man, Pimp C, and B-U-N B",
      "Nigga it's the - big Southern rap impresario",
      "Comin straight up out the black bar-rio",
      "Makes a mill' up off a sorry hoe",
      "Then sit back and peep my sce-nawr-e-oh",
      "Oops, my bad, that's my scenario",
      "No I can't fuck a scary hoe",
      "Now every time, every place, everywhere we go",
      "Hoes start pointin - they say, \"There he go!\"",
      "Now these motherfuckers know we carry mo' heat than a little bit",
      "We don't pull it out over little shit",
      "And if you catch a lick when I spit, then it won't be a little hit",
      "Go read a book you illiterate son of a bitch and step up yo' vocab",
      "Don't be surprised if yo' hoe stab out with me",
      "and you see us comin down on yo' slab",
      "Livin ghetto-fabulous, so mad, you just can't take it",
      "But nigga if you hatin I",
      "then you wait while I get yo' bitch butt-naked, just break it",
      "You gotta pay like you weigh wet wit two pairs of clothes on",
      "Now get yo' ass to the back as I'm flyin to the track",
      "Timbaland let me spit my pro's on",
      "Pump it up in the pro-zone",
      "That's the track that we breakin these hoes on",
      "Ain't the track that we flow's on",
      "But when shit get hot, then the glock start poppin like ozone",
      "We keep hoes crunk like Trigger-man",
      "Fo' real it don't get no bigger man",
      "Don't trip, let's flip, gettin throwed on the flip",
      "Gettin blowed with the motherfuckin Jigga Man, fool",
      "We be.. big pimpin, spendin G's",
      "We be.. big pimpin, on B.L.A.D.'s",
      "We be.. big pimpin down in P.A.T.",
      "It's just that Jigga Man, Pimp C, and B-U-N B",
      "Cause we be.. big pimpin, spendin G's",
      "And we be.. big pimpin, on B.L.A.D.'s",
      "Cause we be.. big pimpin in P.A.T.",
      "It's just that Jigga Man, Pimp C, and B-U-N B.. nigga",
      "Uhh.. smokin out, throwin up, keepin lean up in my cup",
      "All my car got leather and wood, in my hood we call it buck",
      "Everybody wanna ball, holla at broads at the mall",
      "If he up, watch him fall, nigga I can't fuck witch'all",
      "If I wasn't rappin baby, I would still be ridin Mercedes",
      "Chromin shinin sippin daily, no rest until whitey pay me",
      "Uhhh, now what y'all know bout them Texas boys",
      "Comin down in candied toys, smokin weed and talkin noise",
      "Uhh, uh uh uh",
      "It's big pimpin baby..",
      "It's big pimpin, spendin G's",
      "Feel me.. uh-huh uhh, uh-huh..",
      "Ge-ge-geyeah, geyeah",
      "Ge-ge-geyeah, geyeah..",
      "You know I - thug em, fuck em, love em, leave em",
      "Cause I don't fuckin need em",
      "Take em out the hood, keep em lookin good",
      "But I don't fuckin feed em",
      "First time they fuss I'm breezin",
      "Talkin bout, \"What's the reasons?\"",
      "I'm a pimp in every sense of the word, bitch",
      "Better trust than believe em",
      "In the cut where I keep em",
      "til I need a nut, til I need to beat the guts",
      "Then it's, beep beep and I'm pickin em up",
      "Let em play with the dick in the truck",
      "Many chicks wanna put Jigga fist in cuffs",
      "Divorce him and split his bucks",
      "Just because you got good head, I'ma break bread",
      "so you can be livin it up? Shit I..",
      "parts with nothin, y'all be frontin",
      "Me give my heart to a woman?",
      "Not for nothin, never happen",
      "I'll be forever mackin",
      "Heart cold as assassins, I got no passion",
      "I got no patience",
      "And I hate waitin..",
      "Hoe get yo' ass in",
      "And let's RI-I-I-I-I-IDE.. check em out now",
      "RI-I-I-I-I-IDE, yeah",
      "And let's RI-I-I-I-I-IDE.. check em out now",
      "RI-I-I-I-I-IDE, yeah",
      "We doin.. big pimpin, we spendin G's",
      "Check em out now",
      "Big pimpin, on B.L.A.D.'s",
      "We doin.. big pimpin up in N.Y.C.",
      "It's just that Jigga Man, Pimp C, and B-U-N B",
      "Yo yo yo.. big pimpin, spendin G's",
      "We doin - big pimpin, on B.L.A.D.'s",
      "We doin.. big pimpin up in N.Y.C.",
      "It's just that Jigga Man, Pimp C, and B-U-N B",
      "Nigga it's the - big Southern rap impresario",
      "Comin straight up out the black bar-rio",
      "Makes a mill' up off a sorry hoe",
      "Then sit back and peep my sce-nawr-e-oh",
      "Oops, my bad, that's my scenario",
      "No I can't fuck a scary hoe",
      "Now every time, every place, everywhere we go",
      "Hoes start pointin - they say, \"There he go!\"",
      "Now these motherfuckers know we carry mo' heat than a little bit",
      "We don't pull it out over little shit",
      "And if you catch a lick when I spit, then it won't be a little hit",
      "Go read a book you illiterate son of a bitch and step up yo' vocab",
      "Don't be surprised if yo' hoe stab out with me",
      "and you see us comin down on yo' slab",
      "Livin ghetto-fabulous, so mad, you just can't take it",
      "But nigga if you hatin I",
      "then you wait while I get yo' bitch butt-naked, just break it",
      "You gotta pay like you weigh wet wit two pairs of clothes on",
      "Now get yo' ass to the back as I'm flyin to the track",
      "Timbaland let me spit my pro's on",
      "Pump it up in the pro-zone",
      "That's the track that we breakin these hoes on",
      "Ain't the track that we flow's on",
      "But when shit get hot, then the glock start poppin like ozone",
      "We keep hoes crunk like Trigger-man",
      "Fo' real it don't get no bigger man",
      "Don't trip, let's flip, gettin throwed on the flip",
      "Gettin blowed with the motherfuckin Jigga Man, fool",
      "We be.. big pimpin, spendin G's",
      "We be.. big pimpin, on B.L.A.D.'s",
      "We be.. big pimpin down in P.A.T.",
      "It's just that Jigga Man, Pimp C, and B-U-N B",
      "Cause we be.. big pimpin, spendin G's",
      "And we be.. big pimpin, on B.L.A.D.'s",
      "Cause we be.. big pimpin in P.A.T.",
      "It's just that Jigga Man, Pimp C, and B-U-N B.. nigga",
      "Uhh.. smokin out, throwin up, keepin lean up in my cup",
      "All my car got leather and wood, in my hood we call it buck",
      "Everybody wanna ball, holla at broads at the mall",
      "If he up, watch him fall, nigga I can't fuck witch'all",
      "If I wasn't rappin baby, I would still be ridin Mercedes",
      "Chromin shinin sippin daily, no rest until whitey pay me",
      "Uhhh, now what y'all know bout them Texas boys",
      "Comin down in candied toys, smokin weed and talkin noise",
      "We're gonna skate to one song and one song only.",
      "So I ball so hard muhfuckas wanna fine me",
      "first niggas gotta find me",
      "What’s 50 grand to a muhfucka like me",
      "Can you please remind me?",
      "Ball so hard, this shit crazy",
      "Y’all don’t know that don’t shit phase me",
      "The Nets could go 0-82 and I look at you like this shit gravy",
      "Ball so hard, this shit weird",
      "We ain’t even supposed to be here,",
      "Ball so hard, since we here",
      "It’s only right that we be fair",
      "Psycho, I’m liable to go Michael",
      "Take your pick, Jackson, Tyson, Jordan, Game 6",
      "Ball so hard, got a broke clock, Rolleys that don’t tick tock",
      "Audemars that’s losing time, hidden behind all these big rocks",
      "Ball so hard, I’m shocked too,",
      "I’m supposed to be locked up too",
      "you escaped what I’ve escaped",
      "You’d be in Paris getting fucked up too",
      "Ball so hard, let’s get faded, Le Meurice for like 6 days",
      "Gold bottles, scold models, spillin’ Ace on my sick J’s",
      "So ball so hard, bitch behave, just might let you meet Ye,",
      "Chi towns D. Rose, I’m movin’ the Nets to BK",
      "Ball so hard muhfuckas wanna fine me",
      "That shit cray",
      "She said Ye can we get married at the mall?",
      "I said look you need to crawl ‘fore you ball",
      "Come and meet me in the bathroom stall",
      "And show me why you deserve to have it all",
      "Ball so hard",
      "That shit cray (that shit cray), ain’t it Jay?",
      "Ball so hard",
      "What she order (what she order), fish filet",
      "Ball so hard",
      "Your whip so cold (whip so cold), this old thing",
      "Ball so hard",
      "Act like you’ll never be around motherfuckers like this again",
      "Bougie girl, grab her hand",
      "Fuck that bitch she don’t wanna dance",
      "Excuse my French but I’m in France (I’m just sayin’)",
      "Prince William’s ain’t do it right if you ask me",
      "Cause I was him I would have married Kate & Ashley",
      "What's Gucci my nigga?",
      "What's Louis my killa?",
      "What's drugs my deala?",
      "What's that jacket, Margiela?",
      "Doctors say I’m the illest",
      "Cause I’m suffering from realness",
      "Got my niggas in Paris",
      "And they going gorillas, huh!",
      "I don't even know what that means.",
      "(No one knows what it means, but it's provocative)",
      "No, it's not, it's gross",
      "(It gets the people going!)",
      "Ball so hard muhfuckas wanna fine me",
      "Ball so hard muhfuckas wanna fine me",
      "You are now watching the throne",
      "Don’t let me get in my zone",
      "These other niggas is lyin’",
      "Actin’ like the summer ain’t mine",
      "I got that hot bitch in my home",
      "You know how many hot bitches I own?",
      "Don’t let me get in my zone",
      "The stars is in the building",
      "They hands is to the ceiling",
      "I know I’m bout to kill it",
      "How you know, I got that feeling",
      "You are now watching the throne",
      "Don’t let me into my zone",
      "I’m definitely in my zone",
      "It makes it easier, easier to bear, yeah",
      "You won't regret it, no no",
      "No, girls they don't forget it",
      "LOVE is their home, happiness, yeah",
      "Squee... squee... squee... squeeze her",
      "Don't tease her, never leave her",
      "Sounds so soulful, don't you agree?",
      "OWW! Uhh",
      "I invented swag",
      "Poppin bottles, puttin supermodels in the cab",
      "Proof...",
      "I guess I got my swagger back, truth",
      "New watch alert, Hublot's",
      "Or the big face Roley, I got two of those",
      "Arm out the window through the city, I maneuver slow",
      "Cock back, snap back, see my cut through the holes; go",
      "\"Damn Yeezy and Hov', where the hell you been?\"",
      "Niggaz talkin real reckless, stuntmen",
      "I adopted these niggaz, Phillip Drummond 'em",
      "Now I'm 'bout to make 'em tuck they whole summer in",
      "They say I'm crazy, well I'm 'bout to go dumb again",
      "They ain't see me cause I pulled up in my other Benz",
      "Last week I was in my other other Benz",
      "Throw your diamonds up cause we in this bitch another 'gain",
      "Yeah, photo shoot fresh, lookin like wealth",
      "I'm 'bout to call the paparazzi on myself",
      "Uh, live from the Mercer",
      "Run up on Yeezy the wrong way I might murk ya",
      "Flee in the G-450 I might surface",
      "Political refugee asylum can be purchased",
      "Uh, everything's for sale",
      "I got five passports, I'm never goin to jail",
      "I made \"Jesus Walks\" I'm never goin to hell",
      "Couture level flow, it's never goin on sale",
      "Luxury rap, the Hermes of verses",
      "Sophisticated ignorance, write my curses in cursive",
      "I get it custom, you a customer",
      "You ain't 'custommed to goin through customs, you ain't been nowhere, huh?",
      "And all the ladies in the house got 'em showin off",
      "I'm done, I'll hit you up maña-naaaaaaaaaa!",
      "Welcome to Havana",
      "Smokin Cubanas with Castro in cabanas",
      "Viva México, Cubano",
      "Dominicano, all the plugs that I know",
      "Drivin Benzes, with no benefits",
      "Not bad, huh? For some immigrants",
      "Build your fences, we diggin tunnels",
      "Can't you see we gettin money up under you?",
      "Can't you see the private jets flyin over you?",
      "Maybach bumper sticker read \"What would Hova do?\"",
      "Jay is chillin (uhh) 'Ye is chillin (uhh)",
      "What more can I say? (What more can I say?) We killin 'em",
      "Hold up, before we end this campaign",
      "As you can see we done bodied the damn lanes",
      "Lord, please let them accept the things they can't change",
      "And pray that all of their pain be champagne"
    ]
  end
end
